#!/usr/bin/env python3
"""
Generate a complete spec site HTML via parallel OpenRouter API calls.

Splits the site into 3 sections (top/middle/bottom), generates each in
parallel with kimi-k2.5, then combines with a deterministic CSS framework.

Usage:
    python3 execution/generate_spec_site.py \
        --research .tmp/acme-hvac/research.json \
        --palette_index 0 \
        --hero_style_index 0 \
        --output .tmp/acme-hvac/index.html

Prerequisites:
    - OPENROUTER_API_KEY in .env
"""

import os
import sys
import json
import argparse
import time
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from dotenv import load_dotenv

load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
MODEL = "moonshotai/kimi-k2.5"

PALETTES = [
    {"name": "Navy/Amber", "primary": "#0B1D3A", "accent": "#D4922A", "light": "#F5F0E8", "text_on_primary": "#FFFFFF"},
    {"name": "Forest/Gold", "primary": "#1B4332", "accent": "#D4A22A", "light": "#F0F5EC", "text_on_primary": "#FFFFFF"},
    {"name": "Charcoal/Red", "primary": "#2D2D2D", "accent": "#C0392B", "light": "#F5F0F0", "text_on_primary": "#FFFFFF"},
    {"name": "Deep Blue/Orange", "primary": "#1A365D", "accent": "#E07C24", "light": "#F0F3F8", "text_on_primary": "#FFFFFF"},
    {"name": "Dark Teal/Yellow", "primary": "#0D4F4F", "accent": "#E8B930", "light": "#F0F5F5", "text_on_primary": "#FFFFFF"},
]

HERO_STYLES = [
    "full-bleed: Gradient background filling entire viewport, centered text with bold CTA button below",
    "split-layout: Text content on left side, decorative gradient/shape on right side, side-by-side",
    "gradient-overlay: Subtle background pattern or decorative shapes with text overlaid on top",
    "diagonal-split: Angled/clipped sections creating dynamic diagonal division between content areas",
]

# Deterministic CSS framework — never generated by LLM
BASE_CSS = """
:root {{
    --primary: {primary};
    --accent: {accent};
    --light: {light};
    --text-on-primary: {text_on_primary};
    --dark: #1a1a1a;
    --gray: #666;
    --light-gray: #e5e5e5;
    --white: #ffffff;
    --max-width: 1200px;
    --section-padding: 80px 20px;
    --radius: 12px;
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: 'Inter', sans-serif; color: var(--dark); line-height: 1.6; background: var(--white); }}
a {{ text-decoration: none; color: inherit; }}
img {{ max-width: 100%; height: auto; }}
.container {{ max-width: var(--max-width); margin: 0 auto; padding: 0 20px; }}

/* Header */
header {{ position: sticky; top: 0; z-index: 1000; background: var(--primary); color: var(--text-on-primary); padding: 15px 0; box-shadow: 0 2px 10px rgba(0,0,0,0.15); }}
header .container {{ display: flex; justify-content: space-between; align-items: center; }}
.logo {{ font-size: 1.5rem; font-weight: 800; letter-spacing: -0.02em; }}
.nav-links {{ display: flex; gap: 25px; align-items: center; list-style: none; }}
.nav-links a {{ color: var(--text-on-primary); font-weight: 500; font-size: 0.95rem; transition: opacity 0.2s; }}
.nav-links a:hover {{ opacity: 0.8; }}
.phone-link {{ color: var(--accent) !important; font-weight: 700 !important; }}
.menu-toggle {{ display: none; background: none; border: none; color: var(--text-on-primary); font-size: 1.5rem; cursor: pointer; padding: 5px; }}

/* Hero */
.hero {{ background: linear-gradient(135deg, var(--primary) 0%, color-mix(in srgb, var(--primary) 80%, black) 100%); color: var(--text-on-primary); padding: 100px 20px; min-height: 70vh; display: flex; align-items: center; }}
.hero h1 {{ font-size: 3rem; font-weight: 800; line-height: 1.15; margin-bottom: 20px; max-width: 700px; }}
.hero p {{ font-size: 1.2rem; opacity: 0.9; margin-bottom: 30px; max-width: 600px; }}
.hero .phone-big {{ font-size: 1.3rem; margin-top: 20px; }}
.hero .phone-big a {{ color: var(--accent); font-weight: 700; }}

/* Trust Bar */
.trust-bar {{ background: var(--light); padding: 30px 20px; }}
.trust-bar .container {{ display: flex; justify-content: center; gap: 50px; flex-wrap: wrap; }}
.trust-item {{ text-align: center; }}
.trust-item .trust-value {{ font-size: 1.5rem; font-weight: 800; color: var(--primary); }}
.trust-item .trust-label {{ font-size: 0.85rem; color: var(--gray); margin-top: 4px; }}

/* Sections */
section {{ padding: var(--section-padding); }}
.section-title {{ font-size: 2rem; font-weight: 800; text-align: center; margin-bottom: 15px; color: var(--dark); }}
.section-subtitle {{ text-align: center; color: var(--gray); max-width: 600px; margin: 0 auto 45px; font-size: 1.05rem; }}
.bg-light {{ background: var(--light); }}

/* Buttons */
.btn {{ display: inline-block; padding: 15px 35px; border-radius: 6px; font-weight: 700; font-size: 1rem; cursor: pointer; transition: transform 0.2s, box-shadow 0.2s; border: none; text-align: center; }}
.btn:hover {{ transform: translateY(-2px); box-shadow: 0 4px 15px rgba(0,0,0,0.2); }}
.btn-accent {{ background: var(--accent); color: var(--white); }}
.btn-primary {{ background: var(--primary); color: var(--text-on-primary); }}
.btn-white {{ background: var(--white); color: var(--primary); }}

/* Cards & Grids */
.card {{ background: var(--white); border-radius: var(--radius); padding: 30px; box-shadow: 0 2px 15px rgba(0,0,0,0.08); transition: transform 0.2s; }}
.card:hover {{ transform: translateY(-4px); }}
.card .icon {{ font-size: 2.2rem; margin-bottom: 15px; }}
.card h3 {{ font-size: 1.15rem; font-weight: 700; margin-bottom: 10px; }}
.card p {{ color: var(--gray); font-size: 0.95rem; }}
.grid {{ display: grid; gap: 25px; }}
.grid-2 {{ grid-template-columns: repeat(2, 1fr); }}
.grid-3 {{ grid-template-columns: repeat(3, 1fr); }}
.grid-4 {{ grid-template-columns: repeat(4, 1fr); }}

/* Reviews */
.review-card {{ background: var(--white); border-radius: var(--radius); padding: 30px; box-shadow: 0 2px 15px rgba(0,0,0,0.08); }}
.stars {{ color: #f59e0b; font-size: 1.1rem; margin-bottom: 12px; }}
.review-text {{ font-style: italic; color: var(--dark); margin-bottom: 15px; line-height: 1.7; }}
.review-author {{ font-weight: 700; color: var(--primary); }}

/* About */
.about-grid {{ display: grid; grid-template-columns: 1.2fr 0.8fr; gap: 50px; align-items: center; }}
.about-text p {{ margin-bottom: 15px; color: var(--gray); }}
.stat-box {{ background: var(--primary); color: var(--text-on-primary); border-radius: var(--radius); padding: 30px; text-align: center; }}
.stat-box .stat-num {{ font-size: 2.5rem; font-weight: 800; color: var(--accent); }}
.stat-box .stat-label {{ font-size: 0.9rem; opacity: 0.85; }}

/* Emergency CTA */
.cta-emergency {{ background: var(--accent); color: var(--white); text-align: center; padding: 70px 20px; }}
.cta-emergency h2 {{ font-size: 2.3rem; font-weight: 800; margin-bottom: 15px; }}
.cta-emergency p {{ font-size: 1.1rem; opacity: 0.9; margin-bottom: 25px; max-width: 600px; margin-left: auto; margin-right: auto; }}
.cta-emergency .cta-phone {{ display: block; font-size: 2.2rem; font-weight: 800; margin-top: 20px; color: var(--white); }}
.cta-emergency .cta-phone:hover {{ text-shadow: 0 0 15px rgba(255,255,255,0.5); }}

/* Service Area */
.service-area {{ text-align: center; padding: 60px 20px; }}
.service-area p {{ max-width: 700px; margin: 0 auto 25px; color: var(--gray); }}

/* Footer */
footer {{ background: var(--primary); color: var(--text-on-primary); padding: 55px 20px 25px; }}
.footer-grid {{ display: grid; grid-template-columns: 1.5fr 1fr 1fr; gap: 40px; }}
footer h3 {{ font-size: 1.1rem; margin-bottom: 18px; color: var(--accent); }}
footer p, footer li {{ opacity: 0.85; font-size: 0.95rem; line-height: 1.8; }}
footer ul {{ list-style: none; }}
footer a {{ color: var(--text-on-primary); opacity: 0.85; transition: opacity 0.2s; }}
footer a:hover {{ opacity: 1; }}
.footer-bottom {{ text-align: center; margin-top: 35px; padding-top: 20px; border-top: 1px solid rgba(255,255,255,0.15); opacity: 0.6; font-size: 0.85rem; }}

/* Responsive */
@media (max-width: 768px) {{
    .menu-toggle {{ display: block; }}
    .nav-links {{ display: none; flex-direction: column; position: absolute; top: 100%; left: 0; right: 0; background: var(--primary); padding: 20px; gap: 15px; box-shadow: 0 5px 15px rgba(0,0,0,0.2); }}
    .nav-links.active {{ display: flex; }}
    .hero {{ padding: 60px 15px; min-height: auto; }}
    .hero h1 {{ font-size: 2rem; }}
    .grid-2, .grid-3, .grid-4 {{ grid-template-columns: 1fr; }}
    .about-grid {{ grid-template-columns: 1fr; }}
    .footer-grid {{ grid-template-columns: 1fr; }}
    .trust-bar .container {{ gap: 25px; }}
    .section-title {{ font-size: 1.6rem; }}
    section {{ padding: 50px 15px; }}
    .cta-emergency .cta-phone {{ font-size: 1.6rem; }}
}}
"""


def _call_openrouter(prompt, max_tokens=5000, label="section"):
    """Single OpenRouter API call with 1 retry."""
    for attempt in range(1, 3):
        try:
            if attempt > 1:
                print(f"    [{label}] Retry...", file=sys.stderr)
                time.sleep(5)

            resp = requests.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": MODEL,
                    "max_tokens": max_tokens,
                    "messages": [{"role": "user", "content": prompt}],
                },
                timeout=180,
            )
            resp.raise_for_status()
            content = resp.json()["choices"][0]["message"]["content"].strip()

            # Strip code fences
            if content.startswith("```"):
                lines = content.split("\n")
                start = 1
                end = len(lines)
                for i in range(len(lines) - 1, 0, -1):
                    if lines[i].strip() == "```":
                        end = i
                        break
                content = "\n".join(lines[start:end])

            if len(content) < 50:
                print(f"    [{label}] Response too short ({len(content)} chars), retrying", file=sys.stderr)
                continue

            return content

        except requests.exceptions.Timeout:
            print(f"    [{label}] Timed out (180s), attempt {attempt}", file=sys.stderr)
        except Exception as e:
            print(f"    [{label}] Error: {e}, attempt {attempt}", file=sys.stderr)

    return None


def generate_spec_site(research_data, palette_index, hero_style_index, output_path):
    """Generate spec site HTML via 3 parallel OpenRouter API calls.

    Args:
        research_data: dict from research.json
        palette_index: int (0-4) for color palette
        hero_style_index: int (0-3) for hero style
        output_path: path to write index.html

    Returns:
        True on success, False on failure
    """
    if not OPENROUTER_API_KEY:
        print("Error: OPENROUTER_API_KEY not set in .env", file=sys.stderr)
        return False

    palette = PALETTES[palette_index % len(PALETTES)]
    hero_style = HERO_STYLES[hero_style_index % len(HERO_STYLES)]

    # Extract research data
    company_name = research_data.get("company_name", "HVAC Company")
    phone = research_data.get("phone", "")
    website = research_data.get("website", "")
    city = research_data.get("city", "")
    state = research_data.get("state", "")
    services = research_data.get("services", [])
    if isinstance(services, list):
        services_str = "\n".join(f"- {s}" for s in services[:8])
    else:
        services_str = str(services)

    reviews = research_data.get("reviews", {})
    if isinstance(reviews, dict):
        avg_rating = reviews.get("average_rating", "")
        review_count = reviews.get("review_count", "")
        review_list = reviews.get("reviews", [])
    else:
        avg_rating = ""
        review_count = ""
        review_list = []

    reviews_str = ""
    for r in review_list[:5]:
        if isinstance(r, dict):
            name = r.get("author", r.get("name", "Customer"))
            text = r.get("text", r.get("review", ""))
            rating = r.get("rating", 5)
            reviews_str += f'- {name} ({rating}/5): "{text}"\n'
        elif isinstance(r, str):
            reviews_str += f"- {r}\n"

    address = research_data.get("address", "")
    if not address and city and state:
        address = f"{city}, {state}"

    about = research_data.get("about", research_data.get("company_description", ""))
    years = research_data.get("years_in_business", "")

    # Shared context injected into all 3 prompts
    shared = f"""Company: {company_name}
Phone: {phone} (always use tel: links for phone numbers)
Address: {address} | City/State: {city}, {state}
Google Rating: {avg_rating}/5 ({review_count} reviews) | Years: {years}

A full CSS framework is already loaded. Use these classes:
- Layout: .container, .grid, .grid-2, .grid-3, .grid-4, .bg-light
- Typography: .section-title, .section-subtitle
- Buttons: .btn .btn-accent, .btn .btn-primary, .btn .btn-white
- Cards: .card (with .icon, h3, p inside), .review-card
- Colors: var(--primary), var(--accent), var(--light), var(--text-on-primary), var(--gray), var(--white)

RULES:
- Output ONLY raw HTML sections. No <!DOCTYPE>, <html>, <head>, <body>, or <style> tags.
- All content is customer-facing (for homeowners, NOT designers).
- Be specific and detailed — write real marketing copy, not placeholder text.
- Use the exact CSS classes listed above. Add inline styles only when necessary.
- NO scroll-reveal or opacity:0 animations."""

    # --- Section 1: Top (header + hero + trust bar) ---
    prompt_top = f"""{shared}

Generate these 3 sections for an HVAC company website:

1. HEADER — <header> with .container inside:
   - <a class="logo">{company_name}</a>
   - <nav class="nav-links"> with links: Services (#services), About (#about), Reviews (#reviews), Contact (#contact)
   - <a class="phone-link" href="tel:{phone}">{phone}</a>
   - <button class="menu-toggle">&#9776;</button>

2. HERO — <section class="hero"> with .container inside. Style: {hero_style}
   - <h1> with a compelling headline about their HVAC services in {city}
   - <p> subheadline about reliability/quality
   - <a class="btn btn-accent" href="tel:{phone}">Get Free Estimate</a>
   - <div class="phone-big">Or call: <a href="tel:{phone}">{phone}</a></div>

3. TRUST BAR — <section class="trust-bar"> with .container inside:
   - 4x <div class="trust-item"> with .trust-value and .trust-label:
     a) Google rating: {avg_rating}/5 with star emoji
     b) {review_count}+ Reviews
     c) {years}+ Years Experience
     d) Licensed & Insured"""

    # --- Section 2: Middle (services + about + reviews) ---
    prompt_mid = f"""{shared}

About the company: {about}

SERVICES:
{services_str}

CUSTOMER REVIEWS (use verbatim — do NOT invent reviews):
{reviews_str if reviews_str else "No reviews available."}

Generate these 3 sections:

4. SERVICES — <section id="services" class="bg-light"> with .container:
   - <h2 class="section-title">Our Services</h2>
   - <p class="section-subtitle"> about comprehensive HVAC solutions
   - <div class="grid grid-3"> of .card items, each with:
     .icon (emoji), <h3>service name</h3>, <p>2-sentence description</p>

5. ABOUT — <section id="about"> with .container:
   - <h2 class="section-title">About {company_name}</h2>
   - <div class="about-grid"> with:
     Left (.about-text): 2-3 paragraphs about the company, their values, expertise
     Right: 2-3 <div class="stat-box"> with .stat-num and .stat-label (years experience, projects completed, satisfaction rate)

6. REVIEWS — <section id="reviews" class="bg-light"> with .container:
   - <h2 class="section-title">What Our Customers Say</h2>
   - <div class="grid grid-3"> of .review-card items, each with:
     <div class="stars">star emojis matching rating</div>
     <p class="review-text">"exact quote"</p>
     <p class="review-author">— Name</p>
   {"- If no reviews provided, show a single card with 'Be Our First Reviewer!' CTA" if not reviews_str else ""}"""

    # --- Section 3: Bottom (CTA + service area + footer + JS) ---
    prompt_bot = f"""{shared}

Generate these sections plus a script tag:

7. EMERGENCY CTA — <section class="cta-emergency">:
   - <h2>24/7 Emergency HVAC Service</h2>
   - <p> about fast response times and expert technicians
   - <a class="btn btn-white" href="tel:{phone}">Call Now</a>
   - <a class="cta-phone" href="tel:{phone}">{phone}</a>

8. SERVICE AREA — <section id="contact" class="service-area">:
   - <h2 class="section-title">Serving {city}, {state} &amp; Surrounding Areas</h2>
   - <p> about their service coverage area, mention nearby cities
   - <a class="btn btn-accent" href="tel:{phone}">Schedule Service Today</a>

9. FOOTER — <footer> with .container:
   - <div class="footer-grid">:
     Column 1: Company name, brief tagline, phone <a href="tel:{phone}">{phone}</a>
     Column 2: <h3>Quick Links</h3> <ul> with li>a for Services, About, Reviews, Contact
     Column 3: <h3>Contact Info</h3> phone, address ({address}), hours (Mon-Sat 7AM-8PM, Sun Emergency Only)
   - <div class="footer-bottom">&copy; 2026 {company_name}. All rights reserved.</div>

10. SCRIPT — <script> tag with:
    - Hamburger toggle: document.querySelector('.menu-toggle') click toggles .nav-links.active
    - Smooth scroll for anchor links (querySelectorAll('a[href^="#"]'))"""

    print(f"Generating spec site for {company_name} (3 parallel sections)...")
    print(f"  Palette: {palette['name']} | Hero: {hero_style.split(':')[0]}")

    start_time = time.time()
    results = {}

    with ThreadPoolExecutor(max_workers=3) as executor:
        futures = {
            executor.submit(_call_openrouter, prompt_top, 5000, "top"): "top",
            executor.submit(_call_openrouter, prompt_mid, 6000, "middle"): "middle",
            executor.submit(_call_openrouter, prompt_bot, 5000, "bottom"): "bottom",
        }
        for future in as_completed(futures):
            section = futures[future]
            result = future.result()
            if result:
                results[section] = result
                elapsed = time.time() - start_time
                print(f"  [{section}] Done: {len(result)} chars ({elapsed:.0f}s)")
            else:
                print(f"  [{section}] FAILED", file=sys.stderr)

    # Check all 3 completed
    missing = [s for s in ["top", "middle", "bottom"] if s not in results]
    if missing:
        print(f"Error: Failed sections: {', '.join(missing)}", file=sys.stderr)
        return False

    # Build CSS with palette colors
    css = BASE_CSS.format(
        primary=palette["primary"],
        accent=palette["accent"],
        light=palette["light"],
        text_on_primary=palette["text_on_primary"],
    )

    # Combine into final HTML document
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{company_name} | Professional HVAC Services in {city}, {state}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>{css}</style>
</head>
<body>

{results['top']}

<main>
{results['middle']}
</main>

{results['bottom']}

</body>
</html>"""

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(html)

    elapsed = time.time() - start_time
    size_kb = len(html) / 1024
    line_count = html.count("\n") + 1
    print(f"  Complete: {output_path} ({size_kb:.1f} KB, {line_count} lines, {elapsed:.0f}s)")
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate spec site HTML via parallel OpenRouter API calls")
    parser.add_argument("--research", required=True, help="Path to research.json")
    parser.add_argument("--palette_index", type=int, default=0, help="Palette index (0-4)")
    parser.add_argument("--hero_style_index", type=int, default=0, help="Hero style index (0-3)")
    parser.add_argument("--output", required=True, help="Output path for index.html")

    args = parser.parse_args()

    with open(args.research, "r") as f:
        research_data = json.load(f)

    success = generate_spec_site(
        research_data=research_data,
        palette_index=args.palette_index,
        hero_style_index=args.hero_style_index,
        output_path=args.output,
    )

    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
